### ISSUE TITLE
Pressing "Max" on Stake Liquidity triggers amount error

### ISSUE THREAD

**Issue by mehowz** [DexterLabZ/bridge.mainnet.zenon.community#12]
When I press "max" on the Stake Liquidity view, the field turns red and errors: Amount is required (while I have the amount required in my balance).

**Comment by uluCthulhu** [comment]
I can't reproduce this issue. Can you consistently reproduce it?

**Comment by mehowz** [comment]
I tried again, and I could no longer reproduce it. I will close the issue.
